version: "3.8"

services:
  db:
    image: mysql:latest
    container_name: tp3-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: tp33
      MYSQL_DATABASE: tp3_db
      MYSQL_USER: tp3
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - tp3-microservice

  discovery:
    build: ./discovery
    container_name: discovery
    ports:
      - "8761:8761"
    networks:
      - tp3-microservice

  gateway:
    build: ./gateway
    container_name: gateway
    depends_on:
      - discovery
    ports:
      - "8080:8080"
      - "5010:5010"
    environment:
      eureka.client.service-url.defaultZone: http://discovery:8761/eureka
    networks:
      - tp3-microservice

  service-utilisateurs:
    build: service-utilisateurs
    container_name: service-utilisateurs
    depends_on:
      - db
      - discovery
    ports:
      - "8081:8081"
      - "5005:5005"
    environment:
      spring.datasource.url: jdbc:mysql://db:3306/tp3_db
      spring.datasource.username: tp3
      spring.datasource.password: 1234
      eureka.client.service-url.defaultZone: http://discovery:8761/eureka
      eureka.client.register-with-eureka: "true"
      eureka.client.fetch-registry: "true"
    networks:
      - tp3-microservice

  service-nouvelles:
    build: service-nouvelles
    container_name: service-nouvelles
    depends_on:
      - db
      - discovery
    ports:
      - "8082:8082"
      - "5007:5005"
    environment:
      spring.datasource.url: jdbc:mysql://db:3306/tp3_db
      spring.datasource.username: tp3
      spring.datasource.password: 1234
      eureka.client.service-url.defaultZone: http://discovery:8761/eureka
      eureka.client.register-with-eureka: "true"
      eureka.client.fetch-registry: "true"
    networks:
      - tp3-microservice

  service-criteres:
    container_name: service-criteres
    build:
      context: ./service-criteres
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "8083:8083"
      - "5006:5005"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/tp3_db
      SPRING_DATASOURCE_USERNAME: tp3
      SPRING_DATASOURCE_PASSWORD: 1234
    depends_on:
      - db
    networks:
      - tp3-microservice

  service-statistiques:
    build: service-statistiques
    container_name: service-statistiques
    depends_on:
      - db
      - discovery
      - service-nouvelles
      - service-criteres
    ports:
      - "8084:8084"
      - "5008:5005"
    environment:
      spring.datasource.url: jdbc:mysql://db:3306/tp3_db
      spring.datasource.username: tp3
      spring.datasource.password: 1234
      eureka.client.service-url.defaultZone: http://discovery:8761/eureka
      eureka.client.register-with-eureka: "true"
      eureka.client.fetch-registry: "true"
    networks:
      - tp3-microservice

volumes:
  mysql_data:

networks:
  tp3-microservice:
    driver: bridge
