services:
  db:
    image: mysql:latest
    container_name: tp3-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tp3_db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  service-criteres:
    container_name: service-criteres
    build:
      context: ./service-criteres
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "8083:8083"
      - "5005:5005"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/tp3_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - db

volumes:
  mysql-data: